### ISSUE TITLE
GamificationInterfaces should create Badges for each BadgeDefinition

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#12]
As pointed out by @gitsteph in https://github.com/mattjegan/django-gamification/pull/11#pullrequestreview-66404983, the `GamificationInterface` is required to create `Badge` instances for each `BadgeDefinition`. It currently does not.

**Comment by Ion-Petcu** [comment]
Hi, I can work at this.

**Comment by Ion-Petcu** [comment]
Create badges after GamificationInterface create https://github.com/mattjegan/django-gamification/pull/20

**Comment by mattjegan** [comment]
You're right, we will need this for all Unlockables as well.
