### ISSUE TITLE
Make the example app a better example

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#23]
The example app might contain a score board, as well as a list of users and badges etc. Buttons down the side to award different things could help demonstrate the underlying logic.

**Comment by sks444** [comment]
@mattjegan, any progress in the example app? :)

**Comment by mattjegan** [comment]
Hey, not as yet but if I get time on the weekend I might have a crack. We're you looking to help out?

**Comment by sks444** [comment]
Yup; I would like to contribute to it when you give it a start :)

**Comment by mattjegan** [comment]
Awesome, thanks for the encouragement. I'll let you know here when I have one up.

**Comment by sks444** [comment]
Thanks, @mattjegan, I will start to contribute in few days. ;)
