### ISSUE TITLE
GamificationInterface is required to populate Unlockables on creation

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#24]
The GamificationInterface is required to create Unlockable instances for each UnlockableDefinition upon creating of a gamification interface. It currently does not.

**Comment by shinning91** [comment]
Isn't GamificationInterface already been used to create Unlockable instances at here?
```
# Create Unlockables for all GamificationInterfaces
            for interface in GamificationInterface.objects.all():
                Unlockable.objects.create_unlockable(self, interface)

```

**Comment by mattjegan** [comment]
Ah yes, you are completely right 👍
