### ISSUE TITLE
Convert tests to use pytest

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#27]
It would be nice if we could use pytest to run the tests as it is very extensible.

**Comment by alanbato** [comment]
Working on it :)

**Comment by mattjegan** [comment]
Thanks @alanbato let me know if you have any questions.

**Comment by fgmacedo** [comment]
Any update on this? Can I contribute to this issue?

**Comment by mattjegan** [comment]
Sure @fgmacedo anyone can contribute 👍
