### ISSUE TITLE
Implement chained badges

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#3]
Add `next_badge = models.ForeignKey('self', null=True)` on `BadgeDefinition` and when the `Badge` is created in the `.save` method, the `Badge.next_badge` field needs to be updated to point at the `Badge` that corresponds with the `BadgeDefinition` it's definition points to.

E.g.
```
BadgeDefA.next_badge ---> BadgeDefB
|
BadgeA.next_badge    ---> BadgeA
```

**Comment by aljp** [comment]
Fixed in PR #11 

Thanks @gitsteph
