### ISSUE TITLE
Add extension for Django REST Framework serializers

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#4]
Add `django_gamification/extensions/drf/` and include a `serializers.py` file with appropriate serializers for each major model.

**Comment by Ion-Petcu** [comment]
Hi, I can take a look at this. Do you want the ForeignKey fields to be replaced by their respective serializers or just remain as a reference?

**Comment by Ion-Petcu** [comment]
Added drf serializers https://github.com/mattjegan/django-gamification/pull/21

**Comment by mattjegan** [comment]
I think just the reference as you implemented were fine, it helps keep a nicer API.
