### ISSUE TITLE
Implement player reset

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/django-gamification#6]

**Comment by Ion-Petcu** [comment]
Hi, I can work at this. I just want to clarify on the intended behaviour: when an interface is reseted, all the badges and unlockable objects will have aquired=False, all the PointChange objects with that interface will be deleted, and for every badge the progress will go back to 0. Is that correct?

**Comment by Ion-Petcu** [comment]
https://github.com/mattjegan/django-gamification/pull/19

**Comment by mattjegan** [comment]
That is correct, your PR was great!
